version: "3.7"
services:
  database:
    image: postgres:latest
    container_name: webdev
    restart: always
    ports:
      - 5455:5432
    environment:
      POSTGRES_DB: gallery
      POSTGRES_PASSWORD: postgres